// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DynamicCRUD.T4Templates
{
    using System.Linq;
    using System.Text;
    using System.Reflection;
    using System.Collections.Generic;
    using System;

    /// <summary>
    /// Class to produce the template output
    /// </summary>

#line 1 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class GenericDataService : GenericDataServiceBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using Ardalis.GuardClauses;\r\nusing AutoMapper;\r\nusing System;\r\nusing System.Colle" +
                    "ctions.Generic;\r\nusing System.Linq;\r\nusing System.Text;\r\nusing System.Threading." +
                    "Tasks;\r\nusing ");

#line 15 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));

#line default
#line hidden
            this.Write(".Repositories;\r\nusing ");

#line 16 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));

#line default
#line hidden
            this.Write(".DTOs;\r\n\r\n\r\nnamespace ");

#line 19 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));

#line default
#line hidden
            this.Write(".Services\r\n{\r\n    public class ");

#line 21 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("DataService : I");

#line 21 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("DataService\r\n    {\r\n        private readonly I");

#line 23 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("Repository _");

#line 23 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository;\r\n\r\n        public ");

#line 25 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("DataService(I");

#line 25 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("Repository ");

#line 25 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository)\r\n        {\r\n            this._");

#line 27 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository = ");

#line 27 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository;\r\n        }\r\n");

#line 29 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"

            if (!string.IsNullOrEmpty(ForeignKeyName))
            {


#line default
#line hidden
                this.Write("        public async Task<List<");

#line 32 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
                this.Write("DTO>> GetAll");

#line 32 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
                this.Write("Async\r\n        (");

#line 33 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ForeignKeyDataType));

#line default
#line hidden
                this.Write(" ");

#line 33 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ForeignKeyName));

#line default
#line hidden
                this.Write(",int pageNumber, int pageSize, string? serverSearchTerm)\r\n        {\r\n            " +
                        "var ");

#line 35 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
                this.Write(" = await _");

#line 35 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
                this.Write("Repository.GetAll");

#line 35 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
                this.Write("Async\r\n            (");

#line 36 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ForeignKeyName));

#line default
#line hidden
                this.Write(", int pageNumber, int pageSize, serverSearchTerm);            \r\n            retur" +
                        "n ");

#line 37 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
                this.Write(".ToList();\r\n        }\r\n");

#line 39 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            }
            else
            {


#line default
#line hidden
                this.Write("        public async Task<List<");

#line 41 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
                this.Write("DTO>> GetAll");

#line 41 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
                this.Write("Async(int pageNumber, int pageSize, string? serverSearchTerm)\r\n        {\r\n       " +
                        "     var ");

#line 43 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
                this.Write(" = await _");

#line 43 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
                this.Write("Repository.GetAll");

#line 43 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
                this.Write("Async( pageNumber, pageSize, serverSearchTerm);\r\n            return ");

#line 44 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
                this.Write(".ToList();\r\n        }\r\n");

#line 46 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            }


#line default
#line hidden
            this.Write("        public async Task<List<");

#line 48 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("DTO>> Search");

#line 48 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
            this.Write("Async(string serverSearchTerm)\r\n        {\r\n            var ");

#line 50 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
            this.Write(" = await _");

#line 50 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository.Search");

#line 50 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
            this.Write("Async(serverSearchTerm);\r\n            return ");

#line 51 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PluralTablename));

#line default
#line hidden
            this.Write(".ToList();\r\n        }\r\n\r\n        public async Task<");

#line 54 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("DTO?> Get");

#line 54 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("ById(");

#line 54 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyDataType));

#line default
#line hidden
            this.Write(" ");

#line 54 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyName));

#line default
#line hidden
            this.Write(")\r\n        {\r\n            var ");

#line 56 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write(" = await _");

#line 56 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository.Get");

#line 56 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("ByIdAsync(");

#line 56 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyName));

#line default
#line hidden
            this.Write(");\r\n            return ");

#line 57 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write(";\r\n        }\r\n        public async Task<");

#line 59 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("DTO?> Add");

#line 59 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("(");

#line 59 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("DTO ");

#line 59 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("DTO)\r\n        {\r\n            Guard.Against.Null(");

#line 61 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("DTO);\r\n            var result = await _");

#line 62 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository.Add");

#line 62 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("Async(");

#line 62 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("DTO);\r\n            if (result == null)\r\n            {\r\n                throw new " +
                    "Exception($\"Add of ");

#line 65 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write(" failed ID: {");

#line 65 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("DTO.");

#line 65 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyName));

#line default
#line hidden
            this.Write("}\");\r\n            }\r\n            return result;\r\n        }\r\n        public async " +
                    "Task<");

#line 69 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("DTO> Update");

#line 69 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("(");

#line 69 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("DTO ");

#line 69 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("DTO, string? username)\r\n        {\r\n            Guard.Against.Null(");

#line 71 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("DTO);\r\n            Guard.Against.Null(username);\r\n            var result = await " +
                    "_");

#line 73 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository.Update");

#line 73 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("Async(");

#line 73 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("DTO);\r\n            if (result == null)\r\n            {\r\n                throw new " +
                    "Exception($\"Update of ");

#line 76 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write(" failed ID: {");

#line 76 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("DTO.");

#line 76 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyName));

#line default
#line hidden
            this.Write("}\");\r\n            }\r\n            return result;\r\n        }\r\n\r\n        public asyn" +
                    "c Task Delete");

#line 81 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("(");

#line 81 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyDataType));

#line default
#line hidden
            this.Write(" ");

#line 81 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyName));

#line default
#line hidden
            this.Write(")\r\n        {\r\n            await _");

#line 83 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository.Delete");

#line 83 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelName));

#line default
#line hidden
            this.Write("Async(");

#line 83 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PrimaryKeyName));

#line default
#line hidden
            this.Write(");\r\n        }\r\n        public async Task<int> GetTotalCount()\r\n        {\r\n       " +
                    "     int result = await _");

#line 87 "C:\Users\MPhil\source\repos\BlazorCRUD_UIGenerator\DynamicCRUD\T4Templates\GenericDataService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelNameCamelCase));

#line default
#line hidden
            this.Write("Repository.GetTotalCountAsync();\r\n            return result;\r\n        }\r\n    }\r\n}" +
                    "");
            return this.GenerationEnvironment.ToString();
        }
    }

#line default
#line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class GenericDataServiceBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0)
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
